#' @title Initialize GSEA Environment Object
#' @description Unified entry point supporting limma-voom (no intercept design) and DESeq2 objects.
#' Automatically extracts contrasts, differential analysis results, and expression matrices to generate
#' a standardized GseaEnv object.
#' @param fit Differential analysis object. Supports \code{MArrayLM} (limma) or \code{DESeqDataSet} (DESeq2).
#' @param pathway_obj Gene set object. Typically generated by \code{build_gsea_pathways()}.
#' @param expr_data Optional. Expression matrix or DGEList. If NULL, extraction from fit object will be attempted (partial support only).
#' @param target_factor Only for DESeq2. Specifies the target factor of interest. If NULL, automatically inferred as the last term in the design formula.
#' @return Returns a standardized object of class \code{GseaEnv}.
#' @export
#' @examples
#' if(interactive()){
#' # Limma workflow
#' design <- model.matrix(~ 0 + group, data = samples)
#' fit <- lmFit(expr, design) %>%
#'   contrasts.fit(cont.matrix) %>%
#'   eBayes()
#' env <- setup_gsea_env(fit, pathway_obj)
#'
#' # DESeq2 workflow
#' dds <- DESeqDataSetFromMatrix(countData, colData, design = ~ batch + group)
#' dds <- DESeq(dds)
#' env <- setup_gsea_env(dds, pathway_obj, target_factor = "group")
#' }
setup_gsea_env <- function(fit, pathway_obj, expr_data = NULL, target_factor = NULL) {
  message("\nStarting GSEAlens engine...")

  # 1. 鏍￠獙鍩哄洜闆嗗璞?
  if (is.null(pathway_obj) || is.null(pathway_obj$TERM2GENE)) {
    stop("Invalid pathway_obj! Please use build_gsea_pathways() to generate a valid gene set object.")
  }

  # 2. 璇嗗埆鍚庣绫诲瀷骞跺垎鍙戞彁鍙?
  backend_data <- NULL
  backend_info <- NULL

  if (inherits(fit, "MArrayLM")) {
    message("Detected input type: [Limma-Voom]")

    # 璋冪敤 Limma 鎻愬彇鍣?
    backend_data <- .extract_limma_data(fit, expr_data)

    backend_info <- list(
      backend = "limma_voom",
      input_class = "MArrayLM",
      design_formula = NULL, # Limma fit 瀵硅薄閫氬父涓嶇洿鎺ヤ繚鐣欏叕寮?
      target_factor = NA
    )
  } else if (inherits(fit, "DESeqDataSet")) {
    message("Detected input type: [DESeq2]")

    # 璋冪敤 DESeq2 鎻愬彇鍣?
    backend_data <- .extract_deseq2_data(fit, target_factor)

    # 璁板綍瀹為檯浣跨敤鐨?target_factor
    actual_factor <- if (is.null(target_factor)) {
      utils::tail(attr(terms(DESeq2::design(fit)), "term.labels"), 1)
    } else {
      target_factor
    }

    backend_info <- list(
      backend = "deseq2",
      input_class = "DESeqDataSet",
      design_formula = DESeq2::design(fit),
      target_factor = actual_factor
    )
  } else {
    stop("Unsupported input type! Please provide MArrayLM (limma) or DESeqDataSet (DESeq2) object.")
  }

  # 3. 缁勮鍩哄洜闆嗕俊鎭?
  #
  geneset_info <- list(
    name = pathway_obj$SuperTag %||% pathway_obj$name,
    term2gene = pathway_obj$TERM2GENE %||% pathway_obj$term2gene,
    meta_dict = {
      md <- pathway_obj$meta_dict %||% pathway_obj$TERM2NAME
      if (!"Subcollection" %in% colnames(md)) md$Subcollection <- ""
      if (!"Combo_Name" %in% colnames(md)) {
        md$Combo_Name <- ifelse(
          is.na(md$Subcollection) | md$Subcollection == "",
          md$Collection,
          paste0(md$Collection, ":", md$Subcollection)
        )
      }
      if (!"Species" %in% colnames(md)) {
        md$Species <- pathway_obj$species %||% "HS"
      }
      md
    },
    used_collections = pathway_obj$collections_used %||% pathway_obj$used_collections,
    species = pathway_obj$species %||% "HS" # 鏂板
  )

  # 4. 鏋勫缓鏈€缁堝璞?
  env_obj <- create_gsea_env(
    backend_info = backend_info,
    contrast_registry = backend_data$contrast_registry,
    de_store = backend_data$de_store,
    expr_bundle = backend_data$expr_bundle,
    geneset = geneset_info,
    raw_obj = list(fit = fit) # 淇濈暀鍘熷瀵硅薄寮曠敤
  )

  # 5. 鏈€缁堟牎楠?
  .check_gsea_env(env_obj)

  message("GseaEnv object built successfully!")
  message(sprintf("   Contains %d contrast groups", nrow(backend_data$contrast_registry)))
  message(sprintf("   Contains %d pathways", nrow(pathway_obj$meta_dict)))

  return(env_obj)
}


# 鏌ョ湅鍑芥暟


#' @title View GSEA Environment Object Overview
#' @description Print detailed information about the GseaEnv object to the console, including backend type,
#' contrast list, and gene set status.
#' @param env_obj GseaEnv object
#' @return Invisibly returns the input object (for chaining).
#' @export

#' @examples
#' if(interactive()){
#' # Placeholder for function example
#' }
inspect_gsea_env <- function(env_obj) {
  if (!inherits(env_obj, "GseaEnv")) stop("Input object is not of class GseaEnv.")

  # 瑙ｆ瀽淇℃伅
  bi <- env_obj$backend_info
  reg <- env_obj$contrast_registry
  gs <- env_obj$geneset
  expr <- env_obj$expr_bundle

  # 鎺у埗鍙拌緭鍑?
  message("")
  message(paste(rep("=", 60), collapse = ""))
  message("       GSEAlens Environment Summary")
  message(paste(rep("=", 60), collapse = ""))

  # 1. 鍚庣淇℃伅
  message("[1] Backend Information")
  message(sprintf("   Type        : %s", bi$backend))
  message(sprintf("   Input Class : %s", bi$input_class))
  if (bi$backend == "deseq2") {
    message(sprintf("   Target Factor: %s", bi$target_factor))
  }
  message("")

  # 2. 瀵规瘮缁勬敞鍐岃〃
  message(sprintf("[2] Contrast Registry (%d comparisons)", nrow(reg)))
  if (nrow(reg) > 0) {
    # 鎵撳嵃鍓嶅嚑涓紝闃叉鍒峰睆
    print_head <- utils::head(reg[, c("contrast_id", "left_group", "right_group")], 5)
    for (i in seq_len(nrow(print_head))) {
      message(sprintf(
        "   [%d] %s  ( %s vs %s )",
        i, print_head$contrast_id[i],
        print_head$left_group[i], print_head$right_group[i]
      ))
    }
    if (nrow(reg) > 5) message("   ... (remaining omitted)")
  } else {
    message("   No contrasts detected!")
  }
  message("")

  # 3. 鍩哄洜闆嗕俊鎭?
  message("[3] Gene Set Database")
  message(sprintf("   Name        : %s", gs$name))
  message(sprintf("   Pathways    : %d", nrow(gs$meta_dict)))
  message("")

  # 4. 琛ㄨ揪鏁版嵁鐘舵€?
  message("[4] Expression Data Status")
  if (!is.null(expr$raw_counts)) {
    message(sprintf(
      "   Raw Counts  : %d genes x %d samples",
      nrow(expr$raw_counts), ncol(expr$raw_counts)
    ))
    message(sprintf("   Display Mat : %s", ifelse(!is.null(expr$display_expr), "Ready", "Missing")))
  } else {
    message("   Expression matrix not included (heatmap functionality will be unavailable)")
  }
  message("")

  # 5. 涓嬩竴姝ユ寚寮?
  message("[5] Next Step")
  message("   Please run the computation engine:")
  message("   > res <- batch_calc_gsea(env_obj)")
  message(paste(rep("=", 60), collapse = ""))

  invisible(env_obj)
}

#' @export
print.GseaEnv <- function(x, ...) {
  inspect_gsea_env(x)
}
