# Section: Capsule Import and GSEA Result Extraction ----

#' @title Load and Smart-Relocate GSEA Computation Capsule
#' @description Safely load a computation capsule. If the file is moved from its
#'   original project path (e.g., copied to desktop), the engine will automatically
#'   restore the standard folder structure in the current working directory and
#'   relocate the capsule. Fully compatible with GseaEnv and GseaRes objects.
#' @param file_path Character. Absolute or relative path to the capsule rds file.
#' @param auto_relocate Logical. Whether to automatically fix the folder structure
#'   and relocate based on the built-in lineage in the current directory? Default TRUE.
#' @param inspect Logical. Whether to automatically print capsule overview after
#'   loading? Default TRUE.
#' @return Returns the parsed GseaRes or GseaEnv capsule object.
#' @export

#' @examples
#' \dontrun{
#' gsea_res <- import_gsea_capsule("/path/to/GSEA_Capsule.rds")
#' }
import_gsea_capsule <- function(file_path, auto_relocate = TRUE, inspect = TRUE) {
  # 1. 鏂囦欢瀛樺湪鎬ф鏌?
  if (!file.exists(file_path)) {
    stop(sprintf("File does not exist: %s", file_path))
  }

  message("Waking up computation capsule...")
  capsule <- readRDS(file_path)

  # 2. 璇嗗埆鑳跺泭绫诲瀷
  if (inherits(capsule, c("GseaEnv", "GseaEnvPro"))) {
    message("Successfully loaded [GseaEnv] environment encapsulation capsule (parallel computation not yet performed).")

    if (inspect && exists("inspect_gsea_env", mode = "function")) {
      inspect_gsea_env(capsule)
    }

    return(invisible(capsule))
  }

  # 3. 瀵逛簬璁＄畻缁撴灉鑳跺泭锛屾墽琛屾櫤鑳藉綊浣嶉€昏緫
  if (!inherits(capsule, "GseaRes")) {
    warning("This file does not appear to be a standard GSEAlens capsule!")
    return(invisible(capsule))
  }

  # 4. 妫€鏌ユ槸鍚︽湁琛€缁熻蹇嗭紙project_info锛?
  project_info <- capsule$metadata$project_info

  if (is.null(project_info)) {
    message("This capsule was generated by an older version and lacks project lineage memory. Loading directly (auto-relocation not possible).")
  } else {
    # 5. 鑾峰彇褰撳墠璺緞涓庨鏈熻矾寰?
    current_abs <- normalizePath(file_path, winslash = "/", mustWork = FALSE)
    expected_abs <- normalizePath(project_info$rds_path, winslash = "/", mustWork = FALSE)

    # 6. 璺緞涓嶄竴鑷达紝涓斿紑鍚簡鑷姩褰掍綅
    if (current_abs != expected_abs && auto_relocate) {
      message("[Lineage Alert] Capsule is currently in a non-standard path")
      message(sprintf("   Current location: %s", current_abs))
      message(sprintf("   Original project: [%s]", project_info$custom_series_name))

      # 7. 鏍规嵁褰撳墠宸ヤ綔鐩綍閲嶅缓鏍囧噯妗ｆ搴?
      local_series_dir <- file.path(getwd(), "GSEA_Output", project_info$custom_series_name)
      if (!dir.exists(local_series_dir)) {
        dir.create(local_series_dir, recursive = TRUE, showWarnings = FALSE)
        message(sprintf("   Created standard archive directory: %s", local_series_dir))
      }

      # 8. 鎵ц鏂囦欢褰掍綅
      target_file <- file.path(local_series_dir, basename(file_path))

      if (!file.exists(target_file) || target_file == current_abs) {
        file.copy(from = file_path, to = target_file, overwrite = TRUE)
        message("   Automatically relocated capsule to standard archive")
        message(sprintf("   New location: %s", target_file))

        # 9. 鏇存柊鑳跺泭鍐呴儴鐨勮矾寰勪俊鎭紝闃叉涓嬫鍔犺浇鏃堕噸澶嶈鍛?
        capsule$metadata$project_info$output_dir <- file.path(getwd(), "GSEA_Output")
        capsule$metadata$project_info$series_dir <- local_series_dir
        capsule$metadata$project_info$rds_path <- target_file
      } else {
        message("   Backup already exists in standard archive (no duplicate needed).")
      }
    }
  }

  # 10. 鑷姩璋冪敤鎺㈤拡鍑芥暟鎵撳嵃姒傚喌
  if (inspect) {
    if (exists("inspect_gsea_res", mode = "function")) {
      inspect_gsea_res(capsule)
    } else {
      message("Successfully loaded [GseaRes] computation result capsule!")
    }
  }

  return(invisible(capsule))
}


#' @title Extract GSEA Results for Specific Contrast
#' @description Extract results for a specified contrast from a GseaRes capsule.
#'   Supports subsetting by gene set collection and automatically recalculates FDR.
#' @param gsea_res GseaRes object (generated by batch_calc_gsea)
#' @param contrast_id String. Contrast group ID (e.g., "A_vs_B").
#' @param target_collection String vector. Gene set collection to extract
#'   (e.g., "H", "C2:CP:KEGG_LEGACY"). Default "ALL" means extract all.
#' @return GseaTask object.
#' @examples
#' \dontrun{
#' task <- extract_gsea_task(gsea_res, contrast_id = "Treatment_vs_Control")
#' }
#' @export
extract_gsea_task <- function(gsea_res, contrast_id, target_collection = "ALL") {
  # 1. 鏍￠獙杈撳叆
  .check_gsea_res(gsea_res)

  if (!(contrast_id %in% names(gsea_res$results))) {
    stop(sprintf(
      "Contrast '%s' not found in results. Available: %s",
      contrast_id, paste(names(gsea_res$results), collapse = ", ")
    ))
  }

  task_info <- gsea_res$results[[contrast_id]]

  if (task_info$status != "Success") {
    stop(sprintf("Contrast '%s' computation failed or has no enrichment results, cannot extract.", contrast_id))
  }

  # 2. 鑾峰彇鍏冧俊鎭?(浠?registry 涓簿纭尮閰嶏紝涓嶅啀瑙ｆ瀽瀛楃涓?
  # 娉ㄦ剰锛歝ontrast_id 鍙兘鏄弽鍚戠殑 (B_vs_A)锛宺egistry 涓彲鑳藉彧鏈夋鍚戠殑 (A_vs_B)
  # 浣嗘垜浠湪 batch_calc_gsea 涓凡缁忔妸鍙嶅悜浠诲姟鍐欏叆浜?results锛屽嵈娌℃湁鍐欏叆 registry (杩欐槸璁捐涓婄殑鏉冭　锛宺egistry 璁板綍鍘熷鐢熺墿瀛﹀姣?
  # 杩欓噷鎴戜滑闇€瑕佹櫤鑳藉鐞?left/right group

  # 浼樺厛浠?results 閲岀殑 genelist 鍚嶇О鎺ㄦ柇 (鏈€鍑嗙‘)
  # 鎴栬€呬粠 registry 鏌ユ壘

  reg <- gsea_res$contrast_registry
  reg_match <- reg[reg$contrast_id == contrast_id, ]

  left_group <- NA
  right_group <- NA

  if (nrow(reg_match) > 0) {
    left_group <- reg_match$left_group[1]
    right_group <- reg_match$right_group[1]
  } else {
    # 濡傛灉 registry 閲屾病鎵惧埌 (鍙兘鏄弽鍚戠敓鎴愮殑浠诲姟)锛屽皾璇曚粠 ID 瑙ｆ瀽
    parts <- strsplit(contrast_id, "_vs_")[[1]]
    if (length(parts) == 2) {
      left_group <- parts[1]
      right_group <- parts[2]
    } else {
      left_group <- contrast_id
      right_group <- "Background"
    }
  }

  # 3. 鎻愬彇 GSEA 缁撴灉瀵硅薄
  gsea_obj <- task_info$data
  res_df <- as.data.frame(gsea_obj@result)

  # 4. 鍒囩墖閫昏緫
  is_slice_mode <- length(target_collection) != 1 || toupper(target_collection[1]) != "ALL"

  if (is_slice_mode) {
    # 鏌ユ壘鍖归厤鐨勮
    # 鏀寔 Collection (濡?"H") 鎴?Combo_Name (濡?"C2:CP:KEGG_LEGACY")
    match_idx <- which(res_df$Collection %in% target_collection |
      res_df$Combo_Name %in% target_collection)

    if (length(match_idx) == 0) {
      stop(sprintf(
        "Slice failed! No pathways found for '%s' in '%s'.",
        contrast_id, paste(target_collection, collapse = ", ")
      ))
    }

    res_df <- res_df[match_idx, , drop = FALSE]

    # 鍏抽敭锛氶噸绠?FDR (娑堥櫎鍏ㄥ簱鑳屾櫙鐨勬儵缃?
    res_df$p.adjust <- p.adjust(res_df$pvalue, method = "BH")
    if ("qvalue" %in% colnames(res_df)) res_df$qvalue <- res_df$p.adjust

    message(sprintf("[Smart Slice] Extracted %d pathways. FDR recalculated.", nrow(res_df)))

    # 鏇存柊 S4 瀵硅薄
    gsea_obj@result <- res_df
  }

  # 5. 鏋勫缓 GseaTask 瀵硅薄
  # 鏁村悎 meta 淇℃伅锛屼緵涓嬫父缁樺浘浣跨敤
  task_meta <- list(
    contrast_id = contrast_id,
    left_group = left_group,
    right_group = right_group,
    geneset_name = ifelse(is_slice_mode,
      paste(target_collection, collapse = "_"),
      gsea_res$geneset_info$name
    ),
    meta_dict = gsea_res$geneset_info$meta_dict,
    expr_bundle = gsea_res$expr_bundle,
    project_info = gsea_res$metadata$project_info,
    backend_info = gsea_res$backend_info
  )

  obj <- create_gsea_task(gsea_res = gsea_obj, meta = task_meta)

  return(obj)
}


# Section: Inspection Functions ----

#' @title View GSEA Result Overview
#' @description Print detailed summary of GseaRes object to console.
#' @param gsea_res GseaRes object
#' @return Invisibly returns the input object (for chaining).
#' @export

#' @examples
#' \dontrun{
#' inspect_gsea_res(gsea_res)
#' }
inspect_gsea_res <- function(gsea_res) {
  if (!inherits(gsea_res, "GseaRes")) stop("Input object is not of GseaRes class.")

  bi <- gsea_res$backend_info
  results <- gsea_res$results

  message("")
  message(paste(rep("=", 60), collapse = ""))
  message("       GSEAlens Result Summary")
  message(paste(rep("=", 60), collapse = ""))

  # 1. 鍚庣淇℃伅
  message("[1] Backend")
  message(sprintf("   Type       : %s", bi$backend))
  message(sprintf("   Run Time   : %s", gsea_res$metadata$run_time))
  message("")

  # 2. 璁＄畻鐘舵€佺粺璁?
  message("[2] Calculation Status")
  status_count <- table(vapply(results, function(x) x$status, character(1)))
  for (name in names(status_count)) {
    icon <- if (name == "Success") "OK" else "FAIL"
    message(sprintf("   %s %s : %d", icon, name, status_count[[name]]))
  }
  message("")

  # 3. 璇︾粏鍒楄〃锛屼慨鏀逛负鍏ㄩ儴鏄剧ず
  message("[3] Contrast Details ")
  n_show <- length(results)
  for (i in seq_len(n_show)) {
    task_name <- names(results)[i]
    task <- results[[i]]

    if (task$status == "Success") {
      n_sig <- sum(task$data@result$p.adjust < 0.05, na.rm = TRUE)
      message(sprintf("   [%d] %-20s | FDR<0.05: %d", i, task_name, n_sig))
    } else {
      message(sprintf("   [%d] %-20s | Failed", i, task_name))
    }
  }
  message("")

  # 4. 涓嬩竴姝ユ寚寮?
  message("[4] Next Step")
  message("   Extract specific results for visualization:")
  message(sprintf('   > task <- extract_gsea_task(gsea_res, "%s")', names(results)[1]))
  message("   > plot_directional_gsea(task, ...)")
  message(paste(rep("=", 60), collapse = ""))

  invisible(gsea_res)
}

#' @export
print.GseaRes <- function(x, ...) {
  inspect_gsea_res(x)
}
