#' @title GSEA Visualization and Report Generation
#' @description Provides static plotting functions and interactive HTML report generation capabilities.
#' @name visualization

NULL

#' @title Plot Directional GSEA
#' @description Professional-grade GSEA plotting engine with seamless support for single or multiple pathway visualization.
#'   Automatically generates elegant legends, intercepts and redraws the classic red-blue gene distribution track.
#' @param directional_gsea_obj A wrapped GseaTask object (returned by extract_gsea_task)
#' @param target_pathways Vector of pathway IDs to plot (supports single or multiple)
#' @param main_title Main title name
#' @param subPlot Controls the number of subplots generated by GseaVis (1: enrichment plot only; 2: enrichment + heatmap track; 3: full rank track)
#' @param curveCol Custom curve color vector
#' @param add_pval Whether to add statistical annotations on the plot. Default FALSE.
#' @param show_contrast_in_axis Logical. Whether to display contrast group information on the x-axis of the Rank plot.
#'   Default FALSE; recommended to set TRUE only in combined canvas mode.
#' @param ... Additional parameters passed to GseaVis::gseaNb
#' @return ggplot2 composite object
#' @importFrom ggplot2 ggplot aes geom_col scale_fill_gradient2 geom_hline scale_x_continuous theme_bw theme element_blank element_text margin coord_cartesian labs geom_vline annotate scale_color_manual
#' @importFrom grDevices colorRampPalette
#' @importFrom patchwork plot_annotation
#' @importFrom stringr str_to_title str_wrap
#' @export
plot_directional_gsea <- function(directional_gsea_obj, target_pathways,
                                  main_title = "GSEA Plot", subPlot = 3,
                                  curveCol = NULL, add_pval = FALSE,
                                  show_contrast_in_axis = FALSE,  # 🔧 新增参数
                                  ...) {

  # 1. 解析对象与提取基础数据
  res <- directional_gsea_obj$gsea_res
  res@result$Description <- res@result$ID #2026-03-25-205956 适配gseaNb制图函数，防止过长的description导致图像异常。
  meta <- directional_gsea_obj$meta
  df <- as.data.frame(res)
  n_lines <- length(target_pathways)
  gList <- res@geneList

  # 2. 高级颜色池分配逻辑
  if (is.null(curveCol) || length(curveCol) < n_lines) {
    base_colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00",
                     "#A65628", "#F781BF", "#1B9E77", "#D95F02", "#7570B3")
    curveCol <- if(n_lines <= length(base_colors)) base_colors[1:n_lines] else grDevices::colorRampPalette(base_colors)(n_lines)
  }

  curveCol_use <- curveCol[1:n_lines]
  curveCol_gsea <- curveCol_use
  if (n_lines == 1) curveCol_gsea <- c(curveCol_use[1], curveCol_use[1])

  # 3. 基础绘图 (原生调用 gseaNb)
  if (!requireNamespace("GseaVis", quietly = TRUE)) {
    stop("Missing 'GseaVis' package. Please install first: devtools::install_github('junjunlab/GseaVis')")
  }

  p_base <- GseaVis::gseaNb(
    object = res,# 2026-03-25-205752 gseaNb强制传递res当中的description作为绘图的列名，因此这里修改没有任何用处，必须强制赋值
    geneSetID = target_pathways,
    subPlot = subPlot,
    addPval = add_pval,
    curveCol = curveCol_gsea,
    ...
  )

  # 4. 终极图例拦截与覆写逻辑
  if (n_lines > 1) {
    df_sub <- df[match(target_pathways, df$ID), ]
    raw_desc <- df_sub$Description
    name_id  <- df_sub$ID

    nice_labels <- sapply(name_id, function(x) {
      tit <- unlist(strsplit(x, split = "_"))
      if (length(tit) > 1) {
        formatted_text <- paste(stringr::str_to_title(tit[2:length(tit)]), collapse = " ")
      } else {
        formatted_text <- paste(stringr::str_to_title(tit), collapse = " ")
      }
      stringr::str_wrap(formatted_text, width = 45)
    })

    names(curveCol_use) <- raw_desc
    override_scale <- ggplot2::scale_color_manual(
      name = "Term Name",
      values = curveCol_use,
      breaks = raw_desc,
      labels = nice_labels
    )

    if (inherits(p_base, "aplot")) {
      p_base$plotlist[[1]] <- p_base$plotlist[[1]] + override_scale
      if (subPlot >= 2 && !is.null(p_base$plotlist[[2]])) {
        p_base$plotlist[[2]] <- p_base$plotlist[[2]] + override_scale
      }
    } else {
      p_base[[1]] <- p_base[[1]] + override_scale
      if (subPlot >= 2 && !is.null(p_base[[2]])) {
        p_base[[2]] <- p_base[[2]] + override_scale
      }
    }
  }

  # 5. 原生经典红蓝底部分布图（🔧 修改：条件显示对比组）
  if (subPlot == 3) {
    df_rank <- data.frame(x = seq_along(gList), y = as.numeric(gList))

    # 🔧【关键修改】根据参数决定是否显示对比组信息
    if (isTRUE(show_contrast_in_axis)) {
      # 联合画布模式：显示对比组
      x_axis_label <- sprintf(
        "%s vs %s",
        meta$left_group,
        meta$right_group
      )
    } else {
      # 默认模式：保持原样
      x_axis_label <- "Rank in Ordered Dataset"
    }

    prank_classic <- ggplot2::ggplot(df_rank, ggplot2::aes(x = x, y = y)) +
      ggplot2::geom_col(ggplot2::aes(fill = y), width = 1, color = NA, show.legend = FALSE) +
      ggplot2::scale_fill_gradient2(low = "#08519C", mid = "white", high = "#A50F15", midpoint = 0) +
      ggplot2::geom_hline(yintercept = 0, linewidth = 0.5, color = "black", linetype = "dashed") +
      ggplot2::scale_x_continuous(breaks = seq(0, length(gList), 5000)) +
      ggplot2::theme_bw(base_size = 14) +
      ggplot2::theme(panel.grid = ggplot2::element_blank(),
                     axis.text = ggplot2::element_text(colour = "black"),
                     plot.margin = ggplot2::margin(t = -0.1, r = 0.2, b = 0.2, l = 0.2, unit = "cm")) +
      ggplot2::coord_cartesian(expand = 0) +
      ggplot2::labs(x = x_axis_label, y = "Ranked List")  # 🔧 使用动态标签

    # 🔧【新增】联合画布模式：加粗加大 X 轴标签
    if (isTRUE(show_contrast_in_axis)) {
      prank_classic <- prank_classic +
        ggplot2::theme(
          axis.title.x = ggplot2::element_text(
            face = "bold",      # 加粗
            size = 18#,          # 字号（默认base_size=14，这里加大到16）
            #color = "#2c3e50",  # 深蓝灰色，更醒目
            #margin = ggplot2::margin(t = 10)  # 与图形保持适当间距
          )
        )
    }


    z_cross <- sum(gList > 0); m_rank <- length(gList)
    anno_layers <- list(
      ggplot2::geom_vline(xintercept = z_cross, linetype = "dashed", color = "grey50"),
      ggplot2::annotate("text", x = z_cross, y = 0, label = paste0("Zero cross at ", z_cross),
                        vjust = 1.5, hjust = -0.05, size = 3, color = "grey30"),
      ggplot2::annotate("text", x = m_rank * 0.01, y = max(gList) * 0.85,
                        label = sprintf("'%s' (pos)", meta$left_group),
                        color = "#A50F15", hjust = 0, size = 4, fontface = "italic"),
      ggplot2::annotate("text", x = m_rank * 0.99, y = min(gList) * 0.85,
                        label = sprintf("'%s' (neg)", meta$right_group),
                        color = "#08519C", hjust = 1, size = 4, fontface = "italic")
    )

    if (inherits(p_base, "aplot")) {
      p_base$plotlist[[3]] <- prank_classic + anno_layers
    } else {
      p_base[[3]] <- prank_classic + anno_layers
    }
  }

  # 6. 添加结构化大标题
  p_final <- p_base + patchwork::plot_annotation(
    title = main_title,
    subtitle = sprintf("<- %s | %s ->", meta$left_group, meta$right_group),
    theme = ggplot2::theme(plot.title = ggplot2::element_text(size = 14, face = "bold", hjust = 0.5),
                           plot.subtitle = ggplot2::element_text(size = 12, hjust = 0.5, color = "grey40"))
  )

  return(p_final)
}


# 2. HTML 报告生成 (ComplexHeatmap 升级版)


#' @title Generate GSEA HTML Report
#' @description Automatically avoids column name contamination, intelligently extracts expression matrices from objects,
#' and outputs comfortable web reports with dual p-value display and heatmaps.
#' Uses the ComplexHeatmap engine to draw high-quality heatmaps, perfectly replicating pheatmap aesthetics.
#' @param res_obj GseaTask object
#' @param output_base_dir Output folder path. If left empty (NULL), it will automatically follow the original project location of the calculation capsule.
#' @param p_adjust_cutoff FDR filtering threshold, default 1
#' @param top_plots Number of pathways to plot detailed sub-pages, format c(positive_count, negative_count)
#' @param dpi Resolution for GSEA enrichment plots, default 200
#' @importFrom ComplexHeatmap Heatmap HeatmapAnnotation draw
#' @importFrom circlize colorRamp2
#' @importFrom grid gpar
#' @export
generate_gsea_html_report <- function(res_obj, output_base_dir = NULL,
                                      p_adjust_cutoff = 1, top_plots = c(15, 15),
                                      dpi = 200) {

  if (!requireNamespace("DT", quietly = TRUE)) stop("Missing 'DT' package.")
  if (!requireNamespace("ComplexHeatmap", quietly = TRUE)) stop("Missing 'ComplexHeatmap' package.")
  if (!requireNamespace("circlize", quietly = TRUE)) stop("Missing 'circlize' package.")

  meta <- res_obj$meta
  res <- res_obj$gsea_res
  df <- as.data.frame(res)

  # 1. 自动寻路逻辑
  if (is.null(output_base_dir)) {
    if (!is.null(meta$project_info) && !is.null(meta$project_info$series_dir)) {
      output_base_dir <- file.path(meta$project_info$series_dir,
                                   sprintf("HTML_Report_%s_vs_%s", meta$left_group, meta$right_group))
    } else {
      output_base_dir <- "GSEA_Results"
    }
  }

  bundle_dir <- output_base_dir
  if (!dir.exists(bundle_dir)) dir.create(bundle_dir, recursive = TRUE)
  details_dir <- file.path(bundle_dir, "Details")
  if (!dir.exists(details_dir)) dir.create(details_dir, recursive = TRUE)

  main_html_path <- file.path(bundle_dir, paste0(basename(bundle_dir), ".html"))

  # 2. 核心清洗区
  if (!is.null(meta$meta_dict)) {
    dict_cols <- colnames(meta$meta_dict)
    df_cols <- colnames(df)
    cols_to_add <- setdiff(dict_cols, df_cols)
    safe_dict <- meta$meta_dict %>% dplyr::select(ID, dplyr::any_of(cols_to_add))
    df_clean <- df %>% dplyr::left_join(safe_dict, by = "ID")
  } else {
    df_clean <- df
  }

  df_clean <- df_clean %>%
    dplyr::filter(p.adjust <= p_adjust_cutoff) %>%
    dplyr::mutate(
      Enriched_In = factor(ifelse(NES > 0, meta$left_group, meta$right_group),
                           levels = c(meta$left_group, meta$right_group)),
      Display_Collection = if("Combo_Name" %in% names(.)) Combo_Name else if("Collection" %in% names(.)) Collection else "Unknown",
      Display_Collection = as.factor(ifelse(is.na(Display_Collection), "Unknown", Display_Collection)),
      Pathway_Link = if("URL" %in% names(.)) {
        ifelse(is.na(URL) | URL == "", sprintf("<b>%s</b>", ID),
               sprintf('<a href="%s" target="_blank" style="color: #0056b3; text-decoration: none;">%s</a>', URL, ID))
      } else { sprintf("<b>%s</b>", ID) },
      Description = if("Description.y" %in% names(.)) Description.y else Description
    ) %>%
    dplyr::arrange(desc(abs(NES))) %>%
    dplyr::mutate(Rank = dplyr::row_number())

  if (nrow(df_clean) == 0) {
    message("Warning: No significant pathways under current cutoff. Skipping report generation.")
    return(invisible(NULL))
  }

  # 3. 表达矩阵智能雷达
  message("[Smart Radar] Detecting expression matrix for heatmap plotting...")
  expr_mat <- NULL; cpm_mat <- NULL; sample_meta_sub <- NULL; n_left <- 0

  if (!is.null(meta$expr_bundle)) {
    expr_bundle <- meta$expr_bundle
    sample_meta <- expr_bundle$sample_meta

    if (!is.null(sample_meta) && "group" %in% colnames(sample_meta)) {
      left_samples <- rownames(sample_meta)[sample_meta$group == meta$left_group]
      right_samples <- rownames(sample_meta)[sample_meta$group == meta$right_group]
      target_samples <- c(left_samples, right_samples)

      if (length(target_samples) > 0) {
        message(sprintf("   [Heatmap Ready] Matched samples: Left group (%s) %d | Right group (%s) %d",
                        meta$left_group, length(left_samples), meta$right_group, length(right_samples)))

        # 获取 display_expr (Z-score 底图)
        if (!is.null(expr_bundle$display_expr)) {
          expr_mat <- expr_bundle$display_expr[, target_samples, drop = FALSE]
        } else if (!is.null(expr_bundle$raw_counts)) {
          expr_mat <- log2(expr_bundle$raw_counts[, target_samples, drop = FALSE] + 1)
        }

        # 获取 raw_counts (用于显示数值)
        if (!is.null(expr_bundle$raw_counts)) {
          cpm_mat <- edgeR::cpm(expr_bundle$raw_counts[, target_samples, drop = FALSE], log = FALSE)
        }

        sample_meta_sub <- sample_meta[target_samples, , drop = FALSE]
        n_left <- length(left_samples)
      }
    }
  }

  # 4. 遍历生成子图与详情页
  pos_plot_ids <- df_clean %>% dplyr::filter(NES > 0) %>% dplyr::arrange(desc(NES)) %>% head(top_plots[1]) %>% dplyr::pull(ID)
  neg_plot_ids <- df_clean %>% dplyr::filter(NES < 0) %>% dplyr::arrange(NES) %>% head(top_plots[2]) %>% dplyr::pull(ID)
  target_plot_ids <- c(pos_plot_ids, neg_plot_ids)

  detail_links <- character(nrow(df_clean))

  for (i in seq_len(nrow(df_clean))) {
    pw_id <- df_clean$ID[i]

    if (!(pw_id %in% target_plot_ids)) {
      detail_links[i] <- '<button class="btn btn-sm btn-outline-secondary" disabled style="padding: 2px 10px;">Skipped</button>'
      next
    }

    safe_pw_name <- gsub("[^A-Za-z0-9_.-]", "_", pw_id)
    detail_filename <- sprintf("Detail_Rank%03d_%s.html", i, safe_pw_name)
    gsea_png_name <- sprintf("GSEA_Rank%03d_%s.png", i, safe_pw_name)
    heat_png_name <- sprintf("Heatmap_Rank%03d_%s.png", i, safe_pw_name)

    # 绘制 GSEA 主图
    tryCatch({
      p_gsea <- plot_directional_gsea(res_obj, target_pathways = pw_id, main_title = pw_id, subPlot = 3, add_pval = FALSE)
      ggplot2::ggsave(file.path(details_dir, gsea_png_name), plot = p_gsea, width = 8, height = 6, dpi = dpi, bg = "white")
    }, error = function(e) {
      message(sprintf("Failed to plot %s: %s", pw_id, e$message))
    })

    # 绘制热图 (ComplexHeatmap 升级版)
    heat_html_tag <- "<p class='text-muted' style='margin-top:20px;'>No expression data matched.</p>"
    if (!is.null(expr_mat)) {
      all_genes <- res@geneSets[[pw_id]]
      match_list_idx <- which(toupper(rownames(expr_mat)) %in% toupper(all_genes))
      plot_genes <- rownames(expr_mat)[match_list_idx]

      if (length(plot_genes) >= 2) {
        plot_mat <- expr_mat[plot_genes, , drop = FALSE]
        plot_mat <- plot_mat[apply(plot_mat, 1, var) > 1e-6, , drop = FALSE]

        if (nrow(plot_mat) >= 2) {
          # Z-score 标准化
          z_mat <- t(scale(t(plot_mat)))
          z_mat[is.na(z_mat)] <- 0
          z_mat[z_mat > 1] <- 1
          z_mat[z_mat < -1] <- -1

          # 提取 CPM 数值 (用于显示)
          display_numbers <- round(cpm_mat[rownames(z_mat), , drop = FALSE])

          # ComplexHeatmap 配置
          # 1. 颜色映射 (复刻 pheatmap 的淡蓝-白-亮粉橙)
          col_fun <- circlize::colorRamp2(c(-1, 0, 1), c("#67a9cf", "#f7f7f7", "#ef8a62"))

          # 2. 列注释 (分组条)
          grp_col <- c("#E41A1C", "#377EB8")
          names(grp_col) <- c(meta$left_group, meta$right_group)

          top_ann <- ComplexHeatmap::HeatmapAnnotation(
            Group = sample_meta_sub$group,
            col = list(Group = grp_col),
            annotation_name_gp = grid::gpar(fontsize = 12, fontface = "bold"),
            simple_anno_size = grid::unit(0.6, "cm")
          )

          # 3. 行注释 (Leading Edge, 可选)
          # leading_status <- ifelse(toupper(rownames(z_mat)) %in% toupper(core_genes), "YES", "NO")
          # right_ann <- rowAnnotation(LeadingEdge = leading_status, ...)

          # 4. 单元格渲染函数 (绘制数值)
          cell_fun <- function(j, i, x, y, width, height, fill) {
            val <- display_numbers[i, j]
            # 保持原有设置：固定黑色字体，字号 13
            grid::grid.text(val, x, y, gp = grid::gpar(fontsize = 13, col = "black", fontface = "bold"))
          }

          # 5. 构建 Heatmap 对象
          ht <- ComplexHeatmap::Heatmap(
            z_mat,
            name = "Z-Score",
            col = col_fun,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            column_split = factor(sample_meta_sub$group, levels = c(meta$left_group, meta$right_group)),
            cluster_column_slices = FALSE,
            top_annotation = top_ann,
            cell_fun = cell_fun,
            row_names_gp = grid::gpar(fontsize = 15),
            column_names_gp = grid::gpar(fontsize = 15, fontface = "bold"),
            rect_gp = grid::gpar(col = "white", lwd = 1), # 白色网格线
            show_heatmap_legend = TRUE,
            width = NULL,
            height = NULL
          )

          # 6. 保存图片
          png(file.path(details_dir, heat_png_name),
              width = 800, height = 600, res = 100)
          ComplexHeatmap::draw(ht, merge_legend = TRUE,
                               column_title = sprintf("Row-Scaled Z-Score [-1, 1]\nEnriched in: %s",
                                                      as.character(df_clean$Enriched_In[i])))
          dev.off()

          heat_html_tag <- sprintf("<img src='%s' class='img-fluid shadow-sm border'>", heat_png_name)
        }
      }
    }

    # 拼接 HTML
    html_content <- sprintf('
      <!DOCTYPE html><html><head><meta charset="utf-8"><title>Detail: %s</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"></head>
      <body class="container mt-4 mb-5"><h2 class="text-primary">%s</h2>
      <h6 class="text-muted mb-4">Original ID: %s</h6>
      <p class="lead"><strong>Rank:</strong> %d | <strong>NES:</strong> %.3f | <strong>FDR:</strong> %.4e</p><hr>
      <div class="row mb-5"><div class="col-md-5"><h4 class="mb-3">Enrichment Plot</h4><img src="%s" class="img-fluid border shadow-sm"></div>
      <div class="col-md-7"><h4 class="mb-3">Expression Heatmap</h4><div style="overflow:auto; max-height:800px;">%s</div></div></div>
      </body></html>
    ', pw_id, pw_id, pw_id, i, df_clean$NES[i], df_clean$p.adjust[i], gsea_png_name, heat_html_tag)

    writeLines(html_content, con = file.path(details_dir, detail_filename))
    detail_links[i] <- sprintf('<a href="./Details/%s" target="_blank" class="btn btn-sm btn-success" style="padding: 2px 10px; text-decoration: none;">Dashboard</a>', detail_filename)
  }

  df_clean$Detail_Page <- detail_links

  # 5. 生成主交互式数据表
  display_df <- df_clean %>%
    dplyr::select(Rank, Detail_Page, Pathway = Pathway_Link, Collection = Display_Collection, Enriched_In, Size = setSize, NES, pvalue, p.adjust, Description)

  dt_table <- DT::datatable(
    display_df, rownames = FALSE, escape = FALSE, filter = "top",
    caption = htmltools::tags$caption(style = 'caption-side: top; text-align: center; font-size: 150%; font-weight: bold;',
                                      sprintf("GSEA Report: %s vs %s", meta$left_group, meta$right_group)),
    extensions = c('Buttons', 'Scroller'),
    options = list(dom = 'Bfrtip', deferRender = TRUE, scrollY = 600, scroller = TRUE, pageLength = -1, buttons = c('copy', 'csv', 'excel'), autoWidth = TRUE)
  ) %>%
    DT::formatRound(columns = c('NES'), digits = 3) %>%
    DT::formatSignif(columns = c('pvalue', 'p.adjust'), digits = 4) %>%
    DT::formatStyle('Enriched_In', backgroundColor = DT::styleEqual(c(meta$left_group, meta$right_group), c('#fee0d2', '#deebf7'))) %>%
    DT::formatStyle('NES', color = DT::styleInterval(0, c('blue', 'red')), fontWeight = 'bold')

  old_wd <- getwd()
  setwd(bundle_dir)
  tryCatch({
    htmlwidgets::saveWidget(dt_table, file = basename(main_html_path), selfcontained = FALSE, libdir = "lib",
                            title = sprintf("GSEA Report: %s vs %s [%s]", meta$left_group, meta$right_group, meta$geneset_name))
  }, finally = { setwd(old_wd) })

  message(sprintf("Done! HTML report generated at: %s", bundle_dir))
  return(invisible(bundle_dir))
}
