#' @title GSEAlens Interactive Analysis Workstation (New Architecture)
#' @description Modular Shiny application based on GseaRes object, supporting Limma and DESeq2 dual backends.
#' @param gsea_res GseaRes object (generated by batch_calc_gsea())
#' @return Shiny application object
#' @export
#' @importFrom shiny shinyApp fluidPage titlePanel sidebarLayout sidebarPanel mainPanel
#' @importFrom shiny tabsetPanel tabPanel br tags HTML icon
#' @importFrom shinycssloaders withSpinner
launch_gsea_app <- function(gsea_res) {



  # 校验输入
  if (!inherits(gsea_res, "GseaRes")) {
    stop("Please provide a standard GseaRes object (generated by batch_calc_gsea())")
  }

  # 动态生成 UI
  ui <- shiny::fluidPage(
    shiny::tags$head(
      shiny::tags$style(shiny::HTML("
        .modal-dialog { max-width: 90vw !important; width: 90vw !important; }
        .modal-body { max-height: 85vh; overflow-y: auto; background-color: #fafafa; }
        .white-box {
          background-color: white; padding: 15px; border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 15px;
        }
        .description-cell {
          white-space: normal !important; word-wrap: break-word !important;
          max-width: 300px; font-size: 12px; line-height: 1.4;
        }
        .dt-center { text-align: center !important; }
        .well { background-color: #f8f9fa; border: 1px solid #e9ecef; border-radius: 8px; padding: 15px; }
      "))
    ),
    shiny::titlePanel(shiny::HTML("GSEAlens: Seek Inside")),
    shiny::sidebarLayout(
      shiny::sidebarPanel(
        width = 3,
        mod_data_prep_ui("data_prep")
      ),
      shiny::mainPanel(
        width = 9,
        shiny::tabsetPanel(
          id = "main_tabs",
          shiny::tabPanel(
            title = "Main Workspace",
            shiny::br(),
            mod_master_table_ui("master_table"),
            shiny::hr(),
            mod_multi_plot_ui("multi_plot")
          ),
          shiny::tabPanel(
            title = "Holographic Quadruple Linkage",
            shiny::br(),
            mod_quadrant_ui("quadrant")
          ),
          shiny::tabPanel(
            title = "Pathway Relationship Exploration",
            shiny::br(),
            mod_pathway_relation_ui("pathway_relation")
          ),
          shiny::tabPanel(
            title = "Joint GSEA Canvas",
            shiny::br(),
            mod_joint_canvas_ui("joint_canvas")
          )
        )
      )
    ),
    # 隐藏的弹窗占位
    mod_pathway_modal_ui("pathway_modal")
  )

  # Server 逻辑
  server <- function(input, output, session) {

    # 1. 数据预处理模块（返回列表）
    data_prep_list <- mod_data_prep_server("data_prep", gsea_res)

    # 2. 主表格模块（传入 data reactive）
    table_result <- mod_master_table_server("master_table", data_prep_list$data)

    # 3. 联合绘图模块（传入 data reactive）
    mod_multi_plot_server("multi_plot", data_prep_list$data, table_result)

    # 4. 四重联动模块（传入完整列表）
    mod_quadrant_server("quadrant", data_prep_list, gsea_res)

    # 5. 详情弹窗模块（传入 data reactive）
    mod_pathway_modal_server("pathway_modal", data_prep_list$data, table_result$show_modal, gsea_res)

    # 6. 通路关系探索模块（Phase 2）
    mod_pathway_relation_server("pathway_relation", data_prep_list, gsea_res)

    # 7. 联合GSEA画布模块（侧边栏控制版）
    mod_joint_canvas_server("joint_canvas", gsea_res, data_prep_list, table_result)
  }

  message("GSEAlens started")
  message(sprintf("   Backend type: %s", gsea_res$backend_info$backend))
  message(sprintf("   Number of comparison groups: %d", nrow(gsea_res$contrast_registry)))

  shiny::shinyApp(ui, server)
}
