#' @title Generate Pathway Plotting Code
#' @description Generate ready-to-run R code for GSEA pathway visualization.
#'   The generated code includes pathway volcano plot, combined GSEA enrichment
#'   plot, DE volcano plot, and expression boxplot.
#' @param GSEAlens_res GseaRes object
#' @param contrast_id Character. Contrast ID for the analysis
#' @param target_pathways Character vector. Pathway IDs to plot
#' @param user_genes Character vector. Genes of interest to highlight
#' @param expr_type Character. Expression value type (e.g., "logcpm", "vst")
#' @return A character string containing executable R code
#' @export
#' @examples
#' \dontrun{
#' code <- generate_pathway_plot_code(
#'   GSEAlens_res = my_gsea_res,
#'   contrast_id = "A_vs_B",
#'   target_pathways = c("HALLMARK_TNFA_SIGNALING", "REACTOME_APOPTOSIS"),
#'   user_genes = c("TP53", "BCL2", "BAX"),
#'   expr_type = "logcpm"
#' )
#' cat(code)
#' }
generate_pathway_plot_code <- function(GSEAlens_res,
                                       contrast_id,
                                       target_pathways,
                                       user_genes = character(0),
                                       expr_type = "logcpm") {

  # Extract necessary information
  GSEAlens_task <- tryCatch({
    extract_gsea_task(GSEAlens_res, contrast_id)
  }, error = function(e) {
    stop("Failed to extract task for contrast '", contrast_id, "': ", e$message)
  })

  left_group <- GSEAlens_task$meta$left_group
  right_group <- GSEAlens_task$meta$right_group

  # Color palette
  colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#A65628", "#F781BF", "#999999")
  color_str <- paste(colors[seq_len(min(4, length(target_pathways)))], collapse = '", "')

  # Format pathway vector
  pathways_str <- paste(sprintf('    "%s"', target_pathways), collapse = ",\n")

  # Format user genes vector
  if (length(user_genes) > 0) {
    genes_str <- paste(sprintf('    "%s"', user_genes), collapse = ",\n")
  } else {
    genes_str <- "    # No genes of interest specified"
  }

  # Build code
  code <- sprintf('
# =============================================================================
# GSEAlens Static Plotting Code
# Generated by GSEAlens Shiny App
# =============================================================================

# Step 1: Load your GseaRes object
# Replace "YOUR_GSEA_RES_OBJECT" with your actual variable name
GSEAlens_res <- YOUR_GSEA_RES_OBJECT

# Step 2: Extract task for the specified contrast
GSEAlens_task <- extract_gsea_task(GSEAlens_res, contrast_id = "%s")
GSEAlens_left_group <- "%s"
GSEAlens_right_group <- "%s"

# Step 3: Define pathways to plot
GSEAlens_pathways <- c(
%s
)

# Step 4: Define genes of interest (optional)
GSEAlens_genes <- c(
%s
)

# Step 5: Load required libraries
library(GSEAlens)
library(ggplot2)
library(patchwork)
library(ggrepel)

# -----------------------------------------------------------------------------
# 5.1 Combined GSEA Enrichment Plot
# -----------------------------------------------------------------------------
GSEAlens_combined_plot <- plot_directional_gsea(
  directional_gsea_obj = GSEAlens_task,
  target_pathways = GSEAlens_pathways,
  subPlot = 3,
  curveCol = c("%s"),
  main_title = sprintf("Combined: %%d Pathways", length(GSEAlens_pathways))
)
print(GSEAlens_combined_plot)

# -----------------------------------------------------------------------------
# 5.2 DE Volcano Plot with ggrepel Labels
# -----------------------------------------------------------------------------
GSEAlens_de_df <- get_de_table(GSEAlens_res, contrast_id = "%s")

# Prepare data for plotting
GSEAlens_de_df$GSEAlens_category <- "other"
GSEAlens_user_upper <- toupper(GSEAlens_genes)
GSEAlens_de_df$GSEAlens_category[toupper(GSEAlens_de_df$gene_symbol) %%in%% GSEAlens_user_upper] <- "user"

GSEAlens_logfc_thresh <- 1
GSEAlens_pval_thresh <- 0.05
GSEAlens_de_df$GSEAlens_significant <- abs(GSEAlens_de_df$logFC) > GSEAlens_logfc_thresh & GSEAlens_de_df$pvalue < GSEAlens_pval_thresh

# Define colors
GSEAlens_color_map <- c(
  "user" = "#4DAF4A",
  "up" = "#E41A1C",
  "down" = "#377EB8",
  "other" = "#C0C0C0"
)

# Create volcano plot with ggrepel labels (only for user genes)
GSEAlens_volcano_plot <- ggplot(GSEAlens_de_df, aes(x = logFC, y = -log10(pvalue))) +
  geom_point(aes(color = GSEAlens_category), alpha = 0.6, size = 3) +
  # Add ggrepel labels only for user genes
  ggrepel::geom_text_repel(
    data = GSEAlens_de_df[GSEAlens_de_df$GSEAlens_category == "user", ],
    aes(label = gene_symbol),
    size = 3,
    max.overlaps = 50,
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "#4DAF4A",
    segment.alpha = 0.5,
    color = "#4DAF4A",
    fontface = "bold"
  ) +
  scale_color_manual(
    values = GSEAlens_color_map,
    breaks = c("user", "up", "down", "other"),
    labels = c("User Genes", "Up-regulated", "Down-regulated", "Not Significant")
  ) +
  labs(
    title = sprintf("%%s vs %%s - DE Volcano", GSEAlens_left_group, GSEAlens_right_group),
    subtitle = sprintf(
      "User genes: %%d | Up: %%d | Down: %%d",
      sum(GSEAlens_de_df$GSEAlens_category == "user"),
      sum(GSEAlens_de_df$GSEAlens_significant & GSEAlens_de_df$logFC > 0),
      sum(GSEAlens_de_df$GSEAlens_significant & GSEAlens_de_df$logFC < 0)
    ),
    x = "log2 Fold Change",
    y = "-log10(P-value)"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "gray40")
  ) +
  # Add threshold lines
  geom_vline(xintercept = c(-GSEAlens_logfc_thresh, GSEAlens_logfc_thresh),
             linetype = "dashed", color = "gray50", alpha = 0.7) +
  geom_hline(yintercept = -log10(GSEAlens_pval_thresh),
             linetype = "dashed", color = "gray50", alpha = 0.7)

print(GSEAlens_volcano_plot)

# -----------------------------------------------------------------------------
# 5.3 Save plots to file (optional)
# -----------------------------------------------------------------------------
# ggsave("GSEAlens_combined_plot.pdf", GSEAlens_combined_plot, width = 12, height = 8)
# ggsave("GSEAlens_volcano_plot.pdf", GSEAlens_volcano_plot, width = 10, height = 8)
',
contrast_id,
left_group,
right_group,
pathways_str,
genes_str,
color_str,
contrast_id
  )

return(code)
}


#' @title Generate Joint Canvas Code
#' @description Generate code for the Joint GSEA Canvas (Tab 4)
#' @param GSEAlens_res GseaRes object
#' @param contrast_ids Character vector. Multiple contrast IDs
#' @param target_pathways Character vector. Pathway IDs to plot
#' @param ncol Integer. Number of columns for layout
#' @return A character string containing executable R code
#' @export
generate_joint_canvas_code <- function(GSEAlens_res,
                                       contrast_ids,
                                       target_pathways,
                                       ncol = 2) {

  # Format contrast IDs
  contrasts_str <- paste(sprintf('    "%s"', contrast_ids), collapse = ",\n")

  # Format pathways
  pathways_str <- paste(sprintf('    "%s"', target_pathways), collapse = ",\n")

  # Color palette
  colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#A65628", "#F781BF", "#999999")
  color_str <- paste(colors[seq_len(min(4, length(target_pathways)))], collapse = '", "')

  code <- sprintf('
# =============================================================================
# GSEAlens Joint Canvas Code
# Generated by GSEAlens Shiny App
# =============================================================================

# Step 1: Load your GseaRes object
# Replace "YOUR_GSEA_RES_OBJECT" with your actual variable name
GSEAlens_res <- YOUR_GSEA_RES_OBJECT

# Step 2: Define parameters
GSEAlens_contrasts <- c(
%s
)

GSEAlens_pathways <- c(
%s
)

GSEAlens_ncol <- %d

# Step 3: Load required libraries
library(GSEAlens)
library(ggplot2)
library(patchwork)

# Step 4: Generate plots for each contrast
GSEAlens_plot_list <- list()

for (GSEAlens_i in seq_along(GSEAlens_contrasts)) {
  GSEAlens_contrast_id <- GSEAlens_contrasts[GSEAlens_i]

  # Extract task for this contrast
  GSEAlens_task <- extract_gsea_task(GSEAlens_res, contrast_id = GSEAlens_contrast_id)

  # Generate GSEA plot
  GSEAlens_p <- plot_directional_gsea(
    directional_gsea_obj = GSEAlens_task,
    target_pathways = GSEAlens_pathways,
    subPlot = 3,
    curveCol = c("%s"),
    main_title = sprintf("%%s [%%d pathways]",
                         GSEAlens_contrast_id,
                         length(GSEAlens_pathways)),
    add_pval = FALSE,
    show_contrast_in_axis = TRUE
  )

  GSEAlens_plot_list[[GSEAlens_i]] <- GSEAlens_p
}

# Step 5: Combine plots using patchwork
GSEAlens_combined <- patchwork::wrap_plots(
  GSEAlens_plot_list,
  ncol = GSEAlens_ncol,
  nrow = ceiling(length(GSEAlens_plot_list) / GSEAlens_ncol),
  byrow = TRUE,
  guides = "collect"
) + patchwork::plot_annotation(
  title = sprintf("Joint GSEA Canvas: %%d contrasts x %%d pathways",
                  length(GSEAlens_contrasts),
                  length(GSEAlens_pathways)),
  subtitle = sprintf("Arrangement: %%s",
                    paste(GSEAlens_contrasts, collapse = " -> ")),
  theme = ggplot2::theme(
    plot.title = ggplot2::element_text(size = 14, face = "bold", hjust = 0.5),
    plot.subtitle = ggplot2::element_text(size = 10, color = "gray50", hjust = 0.5)
  )
)

# Step 6: Display combined plot
print(GSEAlens_combined)

# Step 7: Save to file (optional)
# ggsave("GSEAlens_joint_canvas.pdf", GSEAlens_combined, width = 14, height = 10)
',
contrasts_str,
pathways_str,
ncol,
color_str
  )

return(code)
}
