

#' @title Generate Pathway Plotting Code
#' @param GSEAlens_res GseaRes object
#' @param contrast_id Character. Contrast ID
#' @param target_pathways Character vector. Pathway IDs
#' @param user_genes Character vector. Genes of interest
#' @param pathway_genes Character vector. Pathway genes (for coloring)
#' @param expr_type Character. Expression type
#' @return A character string containing executable R code
#' @export
generate_pathway_plot_code <- function(GSEAlens_res,
                                       contrast_id,
                                       target_pathways,
                                       user_genes = character(0),
                                       pathway_genes = character(0),
                                       expr_type = "logcpm") {

  # Extract necessary information
  GSEAlens_task <- tryCatch({
    extract_gsea_task(GSEAlens_res, contrast_id)
  }, error = function(e) {
    stop("Failed to extract task for contrast '", contrast_id, "': ", e$message)
  })

  left_group <- GSEAlens_task$meta$left_group
  right_group <- GSEAlens_task$meta$right_group

  # Color palette
  colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#A65628", "#F781BF", "#999999")
  color_str <- paste(colors[seq_len(min(4, length(target_pathways)))], collapse = '", "')

  # Format pathway vector
  pathways_str <- paste(sprintf('    "%s"', target_pathways), collapse = ",\n")

  # Format user genes vector (no newline)
  if (length(user_genes) > 0) {
    genes_str <- paste0('GSEAlens_genes <- c("', paste(user_genes, collapse = '", "'), '")')
  } else {
    genes_str <- 'GSEAlens_genes <- character(0)  # No genes of interest specified'
  }

  # Format pathway genes vector (no newline)
  if (length(pathway_genes) > 0) {
    pathway_str <- paste0('GSEAlens_pathway_genes <- c("', paste(pathway_genes, collapse = '", "'), '")')
  } else {
    pathway_str <- 'GSEAlens_pathway_genes <- character(0)  # No pathway genes specified'
  }

  # Build code using paste0
  code <- paste0(
'# =============================================================================
# GSEAlens Static Plotting Code
# Generated by GSEAlens Shiny App
# =============================================================================

# Step 1: Load your GseaRes object
GSEAlens_res <- YOUR_GSEA_RES_OBJECT

# Step 2: Extract task for the specified contrast
GSEAlens_task <- extract_gsea_task(GSEAlens_res, contrast_id = "', contrast_id, '")
GSEAlens_left_group <- "', left_group, '"
GSEAlens_right_group <- "', right_group, '"

# Step 3: Define pathways to plot
GSEAlens_pathways <- c(
', pathways_str, '
)

# Step 4: Define genes of interest (optional)
', genes_str, '

# Step 5: Define pathway genes (for coloring)
', pathway_str, '

# Step 6: Load required libraries
library(GSEAlens)
library(ggplot2)
library(patchwork)
library(ggrepel)

# -----------------------------------------------------------------------------
# 6.1 Combined GSEA Enrichment Plot
# -----------------------------------------------------------------------------
GSEAlens_combined_plot <- plot_directional_gsea(
  directional_gsea_obj = GSEAlens_task,
  target_pathways = GSEAlens_pathways,
  subPlot = 3,
  curveCol = c("', color_str, '"),
  main_title = paste0("Combined: ", length(GSEAlens_pathways), " Pathways")
)
print(GSEAlens_combined_plot)

# -----------------------------------------------------------------------------
# 6.2 DE Volcano Plot with ggrepel Labels (Six-Color Aesthetics)
# -----------------------------------------------------------------------------
GSEAlens_de_df <- get_de_table(GSEAlens_res, contrast_id = "', contrast_id, '")

# Thresholds
GSEAlens_logfc_thresh <- 1
GSEAlens_pval_thresh <- 0.05

# Color definitions
GSEAlens_color_map <- c(
  "both" = "#9C27B0",    # Purple: User & Pathway
  "user" = "#4DAF4A",    # Green: User only
  "pathway" = "#FF9800",  # Orange: Pathway only
  "up" = "#E41A1C",      # Red: Up-regulated
  "down" = "#377EB8",     # Blue: Down-regulated
  "ns" = "#C0C0C0"       # Gray: Not significant
)

# Classify genes
GSEAlens_user_upper <- toupper(GSEAlens_genes)
GSEAlens_pathway_upper <- toupper(GSEAlens_pathway_genes)
GSEAlens_de_df$GSEAlens_is_user <- toupper(GSEAlens_de_df$gene_symbol) %in% GSEAlens_user_upper
GSEAlens_de_df$GSEAlens_is_pathway <- toupper(GSEAlens_de_df$gene_symbol) %in% GSEAlens_pathway_upper
GSEAlens_de_df$GSEAlens_is_significant <- abs(GSEAlens_de_df$logFC) > GSEAlens_logfc_thresh & GSEAlens_de_df$pvalue < GSEAlens_pval_thresh

# Assign category colors
GSEAlens_de_df$GSEAlens_category <- dplyr::case_when(
  GSEAlens_de_df$GSEAlens_is_user & GSEAlens_de_df$GSEAlens_is_pathway ~ "both",
  GSEAlens_de_df$GSEAlens_is_user ~ "user",
  GSEAlens_de_df$GSEAlens_is_pathway ~ "pathway",
  GSEAlens_de_df$GSEAlens_is_significant & GSEAlens_de_df$logFC > 0 ~ "up",
  GSEAlens_de_df$GSEAlens_is_significant & GSEAlens_de_df$logFC < 0 ~ "down",
  TRUE ~ "ns"
)

# Assign plot order (higher = on top layer)
GSEAlens_de_df$GSEAlens_plot_order <- dplyr::case_when(
  GSEAlens_de_df$GSEAlens_is_user & GSEAlens_de_df$GSEAlens_is_pathway ~ 5,  # both - top layer
  GSEAlens_de_df$GSEAlens_is_user ~ 4,  # user
  GSEAlens_de_df$GSEAlens_is_pathway ~ 3,  # pathway
  GSEAlens_de_df$GSEAlens_is_significant ~ 2,  # up/down
  TRUE ~ 1  # ns - bottom layer
)

# Sort by plot order (draw bottom layer first, top layer last)
GSEAlens_de_df <- GSEAlens_de_df[order(GSEAlens_de_df$GSEAlens_plot_order), ]

# Statistics
GSEAlens_n_up <- sum(GSEAlens_de_df$GSEAlens_is_significant & GSEAlens_de_df$logFC > 0, na.rm = TRUE)
GSEAlens_n_down <- sum(GSEAlens_de_df$GSEAlens_is_significant & GSEAlens_de_df$logFC < 0, na.rm = TRUE)
GSEAlens_n_ns <- sum(!GSEAlens_de_df$GSEAlens_is_significant, na.rm = TRUE)
GSEAlens_n_user <- sum(GSEAlens_de_df$GSEAlens_is_user, na.rm = TRUE)
GSEAlens_n_pathway <- sum(GSEAlens_de_df$GSEAlens_is_pathway, na.rm = TRUE)
GSEAlens_n_both <- sum(GSEAlens_de_df$GSEAlens_is_user & GSEAlens_de_df$GSEAlens_is_pathway, na.rm = TRUE)

# Create volcano plot
GSEAlens_volcano_plot <- ggplot(GSEAlens_de_df, aes(x = logFC, y = -log10(pvalue))) +
  geom_point(aes(color = GSEAlens_category), alpha = 0.6, size = 3) +
  # Add ggrepel labels for both and user genes
  ggrepel::geom_text_repel(
    data = GSEAlens_de_df[GSEAlens_de_df$GSEAlens_is_user, ],
    aes(label = gene_symbol),
    size = 3,
    max.overlaps = 50,
    box.padding = 0.3,
    point.padding = 0.2,
    segment.alpha = 0.5,
    fontface = "bold",
    # Color based on is_pathway: both=purple, user=green
    color = ifelse(GSEAlens_de_df$GSEAlens_is_user[GSEAlens_de_df$GSEAlens_is_user] & GSEAlens_de_df$GSEAlens_is_pathway[GSEAlens_de_df$GSEAlens_is_user], "#9C27B0", "#4DAF4A")
  ) +
  scale_color_manual(
    values = GSEAlens_color_map,
    breaks = c("both", "user", "pathway", "up", "down", "ns"),
    labels = c("Both", "Selected", "Pathway", "Up", "Down", "NS")
  ) +
  labs(
    title = paste0(GSEAlens_left_group, " vs ", GSEAlens_right_group, " - DE Volcano"),
    subtitle = paste0(
  "Both: ", GSEAlens_n_both, " | Selected: ", GSEAlens_n_user, " | Pathway: ", GSEAlens_n_pathway, " | Up: ", GSEAlens_n_up, " | Down: ", GSEAlens_n_down, " | NS: ", GSEAlens_n_ns,
  "\n",
  tail(GSEAlens_pathways, 1)
),
    x = "log2 Fold Change",
    y = "-log10(P-value)"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "gray40", lineheight = 0.8)
  ) +
  geom_vline(xintercept = c(-GSEAlens_logfc_thresh, GSEAlens_logfc_thresh),
             linetype = "dashed", color = "gray50", alpha = 0.7) +
  geom_hline(yintercept = -log10(GSEAlens_pval_thresh),
             linetype = "dashed", color = "gray50", alpha = 0.7)

print(GSEAlens_volcano_plot)

# -----------------------------------------------------------------------------
# 6.3 Save plots to file (optional)
# -----------------------------------------------------------------------------
# ggsave("GSEAlens_combined_plot.pdf", GSEAlens_combined_plot, width = 12, height = 8)
# ggsave("GSEAlens_volcano_plot.pdf", GSEAlens_volcano_plot, width = 10, height = 7)
'
  )

return(code)
}



#' @title Generate Joint Canvas Code
#' @param GSEAlens_res GseaRes object
#' @param contrast_ids Character vector. Multiple contrast IDs
#' @param target_pathways Character vector. Pathway IDs
#' @param ncol Integer. Number of columns
#' @return A character string containing executable R code
#' @export
generate_joint_canvas_code <- function(GSEAlens_res,
                                       contrast_ids,
                                       target_pathways,
                                       ncol = 2) {

  # Format contrast IDs
  contrasts_str <- paste(sprintf('    "%s"', contrast_ids), collapse = ",\n")

  # Format pathways
  pathways_str <- paste(sprintf('    "%s"', target_pathways), collapse = ",\n")

  # Color palette
  colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
              "#FF7F00", "#A65628", "#F781BF", "#999999")
  color_str <- paste(colors[seq_len(min(4, length(target_pathways)))], collapse = '", "')

  # Build code
  code <- paste0(
'# =============================================================================
# GSEAlens Joint Canvas Code
# Generated by GSEAlens Shiny App
# =============================================================================

# Step 1: Load your GseaRes object
GSEAlens_res <- YOUR_GSEA_RES_OBJECT

# Step 2: Define parameters
GSEAlens_contrasts <- c(
', contrasts_str, '
)

GSEAlens_pathways <- c(
', pathways_str, '
)

GSEAlens_ncol <- ', ncol, '

# Step 3: Load required libraries
library(GSEAlens)
library(ggplot2)
library(patchwork)

# Step 4: Generate plots for each contrast
GSEAlens_plot_list <- list()

for (GSEAlens_i in seq_along(GSEAlens_contrasts)) {
  GSEAlens_contrast_id <- GSEAlens_contrasts[GSEAlens_i]

  GSEAlens_task <- extract_gsea_task(GSEAlens_res, contrast_id = GSEAlens_contrast_id)

  GSEAlens_p <- plot_directional_gsea(
    directional_gsea_obj = GSEAlens_task,
    target_pathways = GSEAlens_pathways,
    subPlot = 3,
    curveCol = c("', color_str, '"),
    main_title = paste0(GSEAlens_contrast_id, " [", length(GSEAlens_pathways), " pathways]"),
    add_pval = FALSE,
    show_contrast_in_axis = TRUE
  )

  GSEAlens_plot_list[[GSEAlens_i]] <- GSEAlens_p
}

# Step 5: Combine plots using patchwork
GSEAlens_combined <- patchwork::wrap_plots(
  GSEAlens_plot_list,
  ncol = GSEAlens_ncol,
  nrow = ceiling(length(GSEAlens_plot_list) / GSEAlens_ncol),
  byrow = TRUE,
  guides = "collect"
) + patchwork::plot_annotation(
  title = paste0("Joint GSEA Canvas: ", length(GSEAlens_contrasts), " contrasts x ", length(GSEAlens_pathways), " pathways"),
  subtitle = paste0("Arrangement: ", paste(GSEAlens_contrasts, collapse = " -> ")),
  theme = theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, color = "gray50", hjust = 0.5)
  )
)

# Step 6: Display combined plot
print(GSEAlens_combined)

# Step 7: Save to file (optional)
# ggsave("GSEAlens_joint_canvas.pdf", GSEAlens_combined, width = 14, height = 10)
'
  )

return(code)
}
